[manager]
show_hidden=true
show_symlink=true

[plugin]
prepend_previewers = [
    { mime = "text/csv", run = "miller"},
		{ name = "*.md", run = "glow" },
		{ name = "*.ipynb", run = "nbpreview" },
]
