return {
	{
		"neovim/nvim-lspconfig",
		lazy = true,
		config = function()
			-- 	local capabilities = require("blink.cmp").get_lsp_capabilities()
			-- 	local lspconfig = require("lspconfig")
			-- 	local util = require("lspconfig/util")
			--
			-- 	-- Helper function to get Python path for virtualenv support
			-- 	local function get_python_path(workspace)
			-- 		if vim.env.VIRTUAL_ENV then
			-- 			return util.path.join(vim.env.VIRTUAL_ENV, "bin", "python")
			-- 		end
			--
			-- 		-- Search for virtualenv in workspace
			-- 		for _, pattern in ipairs({ "*", ".*" }) do
			-- 			local match = vim.fn.glob(util.path.join(workspace, pattern, "pyvenv.cfg"))
			-- 			if match ~= "" then
			-- 				return util.path.join(util.path.dirname(match), "bin", "python")
			-- 			end
			-- 		end
			--
			-- 		-- Fallback to system Python
			-- 		return exepath("python3") or exepath("python") or "python"
			-- 	end
			--
			-- 	-- Common LSP server configurations
			-- 	local servers = {
			-- 		lua_ls = {},
			-- 		html = {},
			-- 		cssls = {},
			-- 		clangd = {},
			-- 		-- ccls = {
			-- 		-- 	flags = {
			-- 		-- 		debounce_text_changes = 150,
			-- 		-- 	},
			-- 		-- 	cmd = { "/usr/bin/ccls" },
			-- 		-- 	init_options = {
			-- 		-- 		clang = {
			-- 		-- 			extraARGS = { "--stdc++17" },
			-- 		-- 		},
			-- 		-- 	},
			-- 		-- },
			-- 		quick_lint_js = {},
			-- 		texlab = {},
			-- 		zls = {},
			-- 		emmet_language_server = {},
			-- 		taplo = {},
			-- 		-- dartls = {
			-- 		-- 	cmd = { "dart", "language-server", "--protocol=lsp" },
			-- 		-- },
			-- 		gopls = {
			-- 			settings = {
			-- 				gopls = {
			-- 					analyses = {
			-- 						unusedparams = true,
			-- 					},
			-- 					staticcheck = true,
			-- 					gofumpt = true,
			-- 				},
			-- 			},
			-- 		},
			-- 		jinja_lsp = {
			-- 			filetypes = { "html", "htmldjango" },
			-- 		},
			-- 		ts_ls = {},
			-- 		pyright = {
			-- 			settings = {
			-- 				pyright = {
			-- 					disableOrganizeImports = true,
			-- 				},
			-- 				python = {
			-- 					analysis = {
			-- 						ignore = {},
			-- 					},
			-- 				},
			-- 			},
			-- 			before_init = function(_, config)
			-- 				config.settings.python.pythonPath = get_python_path(config.root_dir)
			-- 			end,
			-- 		},
			-- 		svelte = {},
			-- 		jdtls = {},
			-- 		yamlls = {},
			-- 	}
			--
			-- 	-- Setup all servers with capabilities
			-- 	for server, config in pairs(servers) do
			-- 		vim.lsp.config(server, config)
			-- 		vim.lsp.enable(server)
			-- 	end
			--
			-- 	-- Global LSP keymaps
		end,
	},
}
